- name: testing variable precedence
  hosts: mongodb
  # vars:
  #   NAME: sivakumar-play
  # # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: please enter Trainer name
  #   private: false 
  tasks:
  - name: variable at task level
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"

#1. command lines variables
#2. task level
#3. vars_files
#4. prompt
#5. play
#6. inventory
#7. roles