- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # when you want to run  linux commands directly i.e in the case ansible module not available
    # when the user does not exists, ansible treating this failure and comeout by default
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: output #output is varaible name
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user roboshop
    ansible.builtin.user:
      name: roboshop
    when: output.rc !=0

